variables:
  - name: toolchain
    ask: "Choose a Rust toolchain"
    default_value: "Stable"
    select_in_values:
      - label: "Stable"
        value: "stable"
      - label: "Nightly"
        value: "nightly"
ignores:
  - _default
imports:
  - uri: "{{ ffizer_src_uri }}"
    rev: "{{ ffizer_src_rev }}"
    subfolder: "_default"
